In subspan function, add static checks on extents
ETLCPP/etl pull request #843
Opened 2024-02-14 20:40 UTC by mike919192

Potential fix for issue #842 

etl::span subspan function does not currently statically check extents. std::span does check this.

Code demonstration:
```
std::array<int, 10> array {0};

//std::span std_span1 = std::span(array).subspan<15, 1>(); //compile time error
//std::span std_span2 = std::span(array).subspan<5, 8>(); //compile time error

etl::span etl_span1 = etl::span(array).subspan<15, 1>(); //currently no compile time error
etl::span etl_span2 = etl::span(array).subspan<5, 8>(); //currently no compile time error
```

This PR should enable c++11 and newer to have compile error when the extent check fails.

2024-02-15 11:21 UTC, jwellbelove requested changes
`static_assert` should be replaced with `ETL_STATIC_ASSERT`.

2024-02-15 11:27 UTC, jwellbelove requested changes
The static asserts have no message fields

2024-02-15 14:28 UTC, mike919192 commented
I also realized that the first and last functions also behave similarly, so I have also added the checks for those functions.  I believe those are all the functions where static checks are possible.

```
std::array<int, 10> array {0};

//std::span std_span1 = std::span(array).first<15>(); //compile time error
//std::span std_span2 = std::span(array).last<15>(); //compile time error

etl::span etl_span1 = etl::span(array).first<15>(); //currently no compile time error
etl::span etl_span2 = etl::span(array).last<15>(); //currently no compile time error
```

I don't know if it makes sense to also add the static assert for the pre c++11 subspan function?  I'll await @jwellbelove feedback.

2024-02-15 15:39 UTC, jwellbelove commented
The `ETL_STATIC_ASSERT` will work for pre-C++11 as the macro defines a C++03 static assert implementation.

2024-02-15 17:49 UTC, mike919192 commented
Thanks.  I duplicated the static asserts for the pre c++11 subspan function.  I should be finished with changes unless there are other issues.

2024-02-16 09:21 UTC, jwellbelove approved these changes

2024-02-16 09:21 UTC, merged